### ISSUE TITLE
File submits when attempting to re-select a file

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/GetFoco#113]
**Describe the bug**
In the file-upload step, if an applicant realizes they selected the incorrect file and clicks the 'upload documents' button again, the (incorrect) file submits instead of opening the file selection dialog.

**To Reproduce**
1. Fill out the application, select a program(s) to upload files
2. On the File Upload screen, select 'upload documents' and select a file from the dialog (the 'upload documents' button will turn green because a file was selected)
3. Click the (now-green) 'upload documents' button again to select a different file. The page will refresh and the file selector dropdown will have iterated to the next file (and the page did indeed submit the file in the system as if the 'continue' button was selected).

**Expected behavior**
In the last step of reproducing, the file selection dialog should have opened again and allowed the user to select a different file. The original file would then be replaced by the new file (and the original would never be uploaded to the system).

**Comment by TiCampbell** [comment]
This is an issue with the current prod site as well; it existed before any file-preview changes.

**Comment by penoptech** [comment]
@TiCampbell - I was working on a couple different issues related to the file uploads and tried too see if I could replicate this, but was unable to do so.

I was working on:
OS: macOS 13.2.1 (22D68)
Browser: Chrome Version 111.0.5563.64 (Official Build) (arm64)

Do you mind retesting and dropping in your OS and browser versions?
