### ISSUE TITLE
Recreate 'programs' table with standardized fields

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/GetFoco#141]
Since it's a standard table that applies to all programs, it can have the following fields (not the final format, just an initial idea):

| Field Name | Type | Description |
|:--|:--|:--|
| id | int | Auto-increment id for the table |
| user_id | int | ID that matches to the 'user' table |
| program_id | int | ID that matches to the 'programs' table (the source of truth for each program, e.g. Grocery Tax Rebate) |
| applied_at | timestamp | Timestamp for when the user applied for this program |
| enrolled_at | timestamp | Timestamp for when the user was enrolled in this program |

Also need some sort of qualification state:

| ~~Field Name~~ | ~~Type~~ | ~~Description~~ |
|:--|:--|:--|
| ~~qualified_status~~ | ~~str~~ | ~~Enumeration of qualification status (e.g. 'PENDING', 'ACTIVE', etc) - like the current architecture~~ |

~~OR~~

| ~~Field Name~~ | ~~Type~~ | ~~Description~~ |
|:--|:--|:--|
| ~~is_applied~~ | ~~bool~~ | ~~Designates the user has 'quick applied'~~ |
| ~~is_enrolled~~ | ~~bool~~ | ~~Designates the user has been enrolled~~ |

~~OR~~ `is_applied` can be implied: if there is no record for a program for that user, they haven't applied; if a record exists, the user has 'quick applied'. Then:

| Field Name | Type | Description |
|:--|:--|:--|
| is_enrolled | bool | Designates the user has been enrolled |

**Comment by penoptech** [comment]
If we can drive this content from the database, that would also be ideal. Just not sure where it belongs in the new database model.
```
            'quick_apply_link': reverse('application:IQProgramQuickApply', kwargs={'iq_program': iq_program}),
            'learn_more_link': 'https://www.fcgov.com/recreation/reducedfeeprogram',
            'title': 'Recreation Reduced Fee',
            'subtitle': 'Recreation Assistance',
            'description': 'The Recreation Reduced Fee program provides income-eligible families and residents reduced cost access to recreation programs, classes, and facilities across the community.',
            'supplemental_info': 'Applications accepted all year',
            'eligibility_review_status': "We are reviewing your application! Stay tuned here and check your email for updates." if users_iq_program_status.RecreationQualified == 'PENDING' else "",
            'eligibility_review_time_period': "Estimated Notification Time: Two Weeks" if users_iq_program_status.RecreationQualified == 'PENDING' else "",
            'eligibility_column_name': 'RecreationQualified',
            'program_name': 'recreation',
```

**Comment by TiCampbell** [comment]
@penoptech As usual, we're on the same page! I picture these values in a redesigned `application_iqprogramqualifications` table, where these fields will be in addition to the current `name` and `percentAmi` fields (renamed to something like `program_name` and `ami_threshold`, respectively).

Are these all the data you'd like driven from the database? If so, I'll start a new task to [re]design that table as well.

**Comment by penoptech** [comment]
@TiCampbell - Yes! That would be great. Thinking through this a little more... the `quick_apply_link` and `program_name` likely wouldn't be necessary, since the `iq_program` and `program_name` is the same as the existing `application_iqprogramqualifications.name`.

**Comment by TiCampbell** [comment]
We can also roll the document path into this table:

| Field Name | Type | Description |
|:--|:--|:--|
| document_path | str | Path to the document in Azure Blob Storage |
