### ISSUE TITLE
Redesign IQ Programs table to store program information rather than in the code

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/GetFoco#149]
As discussed in #141, redesign the `application_iqprogramqualifications` table to house program-description information instead of in the code; this will make it easier to add/update program details (and allow non-developers to do so via an admin portal) and we'll no longer have to prepare and deploy code releases to update this information. The new table should look like:

| Field Name | Type | Description |
|:--|:--|:--|
| id | int | Auto-incremented ID |
| program_name | str | Name of the program in Python readability (one word, lowercase; e.g. 'recreation') |
| ami_threshold | decimal | AMI threshold that applicants must be underneath to be eligible |
| friendly_name | str | Name of the program that the users see (e.g. 'Reduced-Fee Recreation') |
| friendly_category | str | Category that the program resides in (e.g. 'Recreation Assistance') |
| friendly_description | str | Description of the program |
| friendly_supplemental_info | str | Supplemental information about the program. This has historically been the application acceptance window (e.g. 'Applications accepted all year') but now that that's the default, recommend leaving blank (`''`) unless further information is necessary. |
| learn_more_link | str | Target for the 'learn more' hyperlink for each program |
| ~~friendly_eligibility_review_status~~ | ~~str~~ | ~~Generic status of the eligibility review (e.g. 'We are reviewing your application! Stay tuned here and check your email for updates.')~~ Removed after discussion (below) |
| friendly_eligibility_review_period | str | Estimated time period for the eligibility review (to be refined with analysis as our systems get better). In code, this will be preceded by 'Estimated Notification Time: ' (or similar), so this value is just value+unit (e.g. 'Two Weeks') |
| created_at | timestamp | Timestamp when the record was created |
| modified_at | timestamp | Timestamp when the record was last modified |

Note that all fields beginning with `friendly_` will be visible to the user.

**Comment by TiCampbell** [comment]
@penoptech RE `eligibility_review_status` - this seems generic enough to me that it could stay in code and not have to be changed. What do you picture this being changed to that it needs to be able to be updated in the database?

**Comment by penoptech** [comment]
@TiCampbell you're spot on. The `eligibility_review_status` doesn't need to be database driven

**Comment by TiCampbell** [comment]
Sounds good, and great call on the latter. I'm going to leave `supplemental_info` so we have some flexibility, with the recommendation to leave it blank.

**Comment by TiCampbell** [comment]
This is now live in `dev` as `application.iqProgramQualifications_rearch` as the IQ Programs lookup table (`application.iq_programs_rearch` is the IQ Programs user table (detailed in #141)). As alluded to in the description, this includes additional "friendly" fields for information that will be pulled into the webapp for the user to see. The ERD for new tables can be found in #154.

Note that, per the Phase 0 rearchitecture specs, these models keep the names of the models they're based on (which is why they're so clunky). Later phases will clean up the naming convention.
